version: '3'

services:
  is_bot:
    container_name: isbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      .env

  db:
    image: postgres:latest
    container_name: isbot_db
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
